### ISSUE TITLE
Program freezes on empty line at the end of team_data.txt

### ISSUE THREAD

**Issue by tyrope** [arkadye/team_picker#1]
I tried to run this on the Blood Pit Bouncers, but the top line doesn't copy nicely due to them being buttons now. I tried to "fake it" but it freezes the program?

Attached is the text file it's trying to parse. I probably did it wrong.

[team_data.txt](https://github.com/user-attachments/files/16319257/team_data.txt)

**Comment by arkadye** [comment]
I'll have a look later. The file needs to be in the same directory as the executable. Is it getting as far as opening the file?

**Comment by tyrope** [comment]
All three files are in the same folder, as is the terminal window that's
accessing the exe.

It's just stuck on "loading team_data.txt", I had it running in the
background for like half an hour with no changes.

**Comment by arkadye** [comment]
I found the issue. It chokes on the empty line at the end. This version work and I'll get round to fixing that bug at some point soon.

[team_data.txt](https://github.com/user-attachments/files/16322210/team_data.txt)
